#!/usr/bin/env bash
# configure a ufw firewall to block all incoming trafic
# exceptfor TCP part 22, 80, and 443.

sudo apt install ufw
sudo ufw default deny incming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo enable
sudo status 
