#!/usr/bin/env bash
# SSH client configuration

Host *
      PasswordAuthentication no
      IdentityFile ~/.shh/shool.
      SendEnv LANG LC_*
      HashKnownHosts yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no
